gpu-context=wayland
vo=gpu
hwdec=vaapi
hwdec-codecs=h264,vp8,vp9
video-sync=display-resample
audio-pitch-correction=yes

# Fullscreen by default
fullscreen=yes

# Prefer English tracks
alang=en,eng
slang=en,eng

autocreate-playlist=same
save-position-on-quit=yes
