# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# custom source
source = ~/.config/hypr/intel-hd4600.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
# Workspaces App Assignment
# Workspace 2 — WEB
windowrule = workspace 2, match:class chromium
windowrule = workspace 2, match:class chrome-claude.ai__-Default

# Workspace 4 — FILES
windowrule = workspace 4, match:class org.gnome.Nautilus

# Workspace 5 — CHAT
windowrule = workspace 5, match:class chrome-web.whatsapp.com__-Default

# Workspace 6 — STUDY
windowrule = workspace 6, match:class org.gnome.Evince

# Workspace 7 — MEDIA
windowrule = workspace 7, match:class mpv
windowrule = workspace 7, match:class chrome-youtube.com__-Default

# Workspace 8 — MUSIC
windowrule = workspace 8, match:class spotify


general {
    col.active_border = rgb(cba6f7) rgb(ef9f76) 45deg
    col.inactive_border = rgba(585b70aa)
    border_size = 2
    gaps_in = 4
    gaps_out = 8
}

animations {
  enabled = true

  # Snappier bezier curve
  bezier = snappy, 0.25, 1, 0.5, 1

  # Windows open/close/move — lower number = faster (default is usually 5–8)
  animation = windows,    1, 2, snappy, slide
  animation = windowsIn,  1, 2, snappy, slide
  animation = windowsOut, 1, 2, snappy, slide
  animation = windowsMove,1, 2, snappy

  # Workspace switching
  animation = workspaces, 1, 3, snappy, slide

  # Fades
  animation = fade,       1, 3, snappy
}
